export global AppIcons {
    out property <image> home: @image-url("../icons/home.svg");
    out property <image> history: @image-url("../icons/history.svg");
    out property <image> star: @image-url("../icons/star.svg");
    out property <image> star_outline: @image-url("../icons/star_outline.svg");
    out property <image> settings: @image-url("../icons/settings.svg");
    out property <image> lan: @image-url("../icons/lan.svg");
    out property <image> lock: @image-url("../icons/lock.svg");
    out property <image> code: @image-url("../icons/code.svg");
    out property <image> fingerprint: @image-url("../icons/fingerprint.svg");
    out property <image> timer: @image-url("../icons/timer.svg");
    out property <image> regex: @image-url("../icons/regex.svg");
    out property <image> swap: @image-url("../icons/swap.svg");
    out property <image> schedule: @image-url("../icons/schedule.svg");
    out property <image> archive: @image-url("../icons/archive.svg");
    out property <image> formatter: @image-url("../icons/formatter.svg");
}
