[package]
name = "devkit"
version = "0.1.7"
edition = "2021"
license = "Apache-2.0"

[lib]
crate-type = ["lib", "cdylib"]
path = "src/lib.rs"
name = "devkit"

[[bin]]
name = "devkit"
path = "src/main.rs"

[dependencies]
slint = { version = "1.18" }
base64 = "0.23"
md5 = "0.8.1"
sha1 = "0.11"
sha2 = "0.11"
blake2 = "0.11"
blake3 = "1.8.7"
hex = "0.4.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
uuid = { version = "1.27", features = [ "v1", "v4", "v7" ] }
mac_address2 = "2"
flate2 = "1.0"

[target.'cfg(target_os = "android")'.dependencies]
slint = { version = "1.18", features = ["backend-android-activity-06", "renderer-skia-vulkan"] }
jni = "0.21"

[build-dependencies]
slint-build = { version = "1.18" }

[package.metadata.android]
package = "it.mtreconsulting.devkit"
apk_name = "devkit"
label = "DevKit"
resources = "res"
target_archs = ["arm64-v8a", "armeabi-v7a", "x86_64"]

[package.metadata.android.sdk]
min_sdk_version = 26
target_sdk_version = 36

[package.metadata.android.application]
label = "DevKit"
icon = "@mipmap/ic_launcher"
round_icon = "@mipmap/ic_launcher_round"

[package.metadata.android.activity]
window_soft_input_mode = "adjustResize"

[package.metadata.android.application.activity]
window_soft_input_mode = "adjustResize"
